# Generated by Django 3.2.8 on 2021-10-30 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apto', models.IntegerField()),
                ('tipo', models.CharField(choices=[('1', 'simples solteiro'), ('2', 'duplo solteiro'), ('3', 'simples casal'), ('4', 'apartamento')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('tipo_classe', models.CharField(choices=[('VIP', 'cliente tipo VIP'), ('NOR', 'cliente normal')], max_length=3)),
                ('cpf', models.IntegerField()),
                ('endereco', models.CharField(max_length=255)),
                ('pessoa_contato', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('Apartamento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.apartamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='hotel.cliente')),
            ],
        ),
    ]
