# Generated by Django 3.2.8 on 2021-11-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reserva_encerrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('preco', models.FloatField()),
                ('estoque', models.IntegerField()),
                ('codigo_barras', models.CharField(max_length=44)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor',
            field=models.FloatField(null=True),
        )
    ]
