# Generated by Django 3.2.8 on 2021-11-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_produto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto_cliente',
            name='valor_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
