# Generated by Django 3.2.8 on 2021-11-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_produto_cliente_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='valor',
            new_name='valor_diaria',
        ),
    ]
