# Generated by Django 3.2.8 on 2021-11-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rename_valor_reserva_valor_diaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='valor_diaria',
            new_name='valor_total',
        ),
    ]
