# Generated by Django 3.2.8 on 2021-11-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_valor_diaria_reserva_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto_cliente',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_total_produtos',
            field=models.FloatField(null=True),
        ),
    ]
